name: tree ZFU
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      # 使用替代方法上传文件
      - name: Prepare Artifact
        run: |
          tar -czf site.tar.gz .
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-artifact
          path: site.tar.gz
          
      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
        with:
          artifact: site-artifact
      
      - name: Show deployment URL
        run: echo "Deployed to ${{ steps.deployment.outputs.page_url }}"
